<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SSend...</name>
   <tag></tag>
   <elementGuidId>a4143f95-1e18-4c4d-af47-dee09dacfac6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>div#lk-container > lk-explore-dataflux > lk-explore-header > div:nth-of-type(2) > div:nth-of-type(2) > ul > li:nth-of-type(5) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>lk-track-name</name>
      <type>Main</type>
      <value>explore</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>openRunOnceDialog()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>⌥⇧SSend...</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lk-container&quot;)/lk-explore-dataflux[@class=&quot;ng-scope ng-isolate-scope&quot;]/lk-explore-header[@class=&quot;lk-page-header lk-title-bar ng-isolate-scope&quot;]/div[@class=&quot;title-controls&quot;]/div[@class=&quot;explore-header-menu ng-scope dropdown open&quot;]/ul[@class=&quot;uib-dropdown-menu dropdown-wide pull-right dropdown-menu&quot;]/li[@class=&quot;ng-scope&quot;]/a[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>div#lk-container > lk-explore-dataflux > lk-explore-header > div:nth-of-type(2) > div:nth-of-type(2) > ul > li:nth-of-type(5) > a</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='lk-container']/lk-explore-dataflux/lk-explore-header/div[2]/div[2]/ul/li[5]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='⇧⌘L'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[2]/ul/li[5]/a</value>
   </webElementXpaths>
</WebElementEntity>
