<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_LookML Dashboards  Dashboa</name>
   <tag></tag>
   <elementGuidId>b508dc2f-7041-4cdc-b35b-c176a4084042</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>div#dashboard</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lk-title-bar</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lk-title</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-show</name>
      <type>Main</type>
      <value>showDashboard()</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LookML Dashboards  DashboardsAgentAgent SummaryCustomer PerformanceLive (In Progress) EventLive EventLive Event SummaryNetwork ContentNetwork LocalityNetwork Readiness TestNetwork SummaryOverviewSCCM SummaryVideo on DemandVideo on Demand SummaryView Space ”LookML Dashboards“OverviewOverviewUsage 7m ago ·  Each Tile's Time Zone (UTC)Viewer Time Zone (UTC)--------------UTCAmerica - ChicagoAmerica - DenverAmerica - JuneauAmerica - Los AngelesAmerica - New YorkAmerica - PhoenixPacific - Honolulu--------------Africa - AbidjanAfrica - AccraAfrica - Addis AbabaAfrica - AlgiersAfrica - AsmaraAfrica - AsmeraAfrica - BamakoAfrica - BanguiAfrica - BanjulAfrica - BissauAfrica - BlantyreAfrica - BrazzavilleAfrica - BujumburaAfrica - CairoAfrica - CasablancaAfrica - CeutaAfrica - ConakryAfrica - DakarAfrica - Dar es SalaamAfrica - DjiboutiAfrica - DoualaAfrica - El AaiunAfrica - FreetownAfrica - GaboroneAfrica - HarareAfrica - JohannesburgAfrica - JubaAfrica - KampalaAfrica - KhartoumAfrica - KigaliAfrica - KinshasaAfrica - LagosAfrica - LibrevilleAfrica - LomeAfrica - LuandaAfrica - LubumbashiAfrica - LusakaAfrica - MalaboAfrica - MaputoAfrica - MaseruAfrica - MbabaneAfrica - MogadishuAfrica - MonroviaAfrica - NairobiAfrica - NdjamenaAfrica - NiameyAfrica - NouakchottAfrica - OuagadougouAfrica - Porto-NovoAfrica - Sao TomeAfrica - TimbuktuAfrica - TripoliAfrica - TunisAfrica - WindhoekAmerica - AdakAmerica - AnchorageAmerica - AnguillaAmerica - AntiguaAmerica - AraguainaAmerica - ArubaAmerica - AsuncionAmerica - AtikokanAmerica - AtkaAmerica - BahiaAmerica - Bahia BanderasAmerica - BarbadosAmerica - BelemAmerica - BelizeAmerica - Beulah, North DakotaAmerica - Blanc-SablonAmerica - Boa VistaAmerica - BogotaAmerica - BoiseAmerica - Buenos AiresAmerica - Buenos Aires, ArgentinaAmerica - Cambridge BayAmerica - Campo GrandeAmerica - CancunAmerica - CaracasAmerica - CatamarcaAmerica - Catamarca, ArgentinaAmerica - CayenneAmerica - CaymanAmerica - Center, North DakotaAmerica - ChihuahuaAmerica - Comod Rivadavia, ArgentinaAmerica - Coral HarbourAmerica - CordobaAmerica - Cordoba, ArgentinaAmerica - Costa RicaAmerica - CrestonAmerica - CuiabaAmerica - CuracaoAmerica - DanmarkshavnAmerica - DawsonAmerica - Dawson CreekAmerica - DetroitAmerica - DominicaAmerica - EdmontonAmerica - EirunepeAmerica - El SalvadorAmerica - EnsenadaAmerica - Fort WayneAmerica - FortalezaAmerica - Glace BayAmerica - GodthabAmerica - Goose BayAmerica - Grand TurkAmerica - GrenadaAmerica - GuadeloupeAmerica - GuatemalaAmerica - GuayaquilAmerica - GuyanaAmerica - HalifaxAmerica - HavanaAmerica - HermosilloAmerica - IndianapolisAmerica - Indianapolis, IndianaAmerica - InuvikAmerica - IqaluitAmerica - JamaicaAmerica - JujuyAmerica - Jujuy, ArgentinaAmerica - Knox I'NAmerica - Knox, IndianaAmerica - KralendijkAmerica - La PazAmerica - La Rioja, ArgentinaAmerica - LimaAmerica - LouisvilleAmerica - Louisville, KentuckyAmerica - Lower PrincesAmerica - MaceioAmerica - ManaguaAmerica - ManausAmerica - Marengo, IndianaAmerica - MarigotAmerica - MartiniqueAmerica - MatamorosAmerica - MazatlanAmerica - MendozaAmerica - Mendoza, ArgentinaAmerica - MenomineeAmerica - MeridaAmerica - MetlakatlaAmerica - Mexico CityAmerica - MiquelonAmerica - MonctonAmerica - MonterreyAmerica - MontevideoAmerica - Monticello, KentuckyAmerica - MontrealAmerica - MontserratAmerica - NassauAmerica - New Salem, North DakotaAmerica - NipigonAmerica - NomeAmerica - NoronhaAmerica - OjinagaAmerica - PanamaAmerica - PangnirtungAmerica - ParamariboAmerica - Petersburg, IndianaAmerica - Port of SpainAmerica - Port-au-PrinceAmerica - Porto AcreAmerica - Porto VelhoAmerica - Puerto RicoAmerica - Rainy RiverAmerica - Rankin InletAmerica - RecifeAmerica - ReginaAmerica - ResoluteAmerica - Rio BrancoAmerica - Rio Gallegos, ArgentinaAmerica - RosarioAmerica - Salta, ArgentinaAmerica - San Juan, ArgentinaAmerica - San Luis, ArgentinaAmerica - Santa IsabelAmerica - SantaremAmerica - SantiagoAmerica - Santo DomingoAmerica - Sao PauloAmerica - ScoresbysundAmerica - ShiprockAmerica - SitkaAmerica - St BarthelemyAmerica - St JohnsAmerica - St KittsAmerica - St LuciaAmerica - St ThomasAmerica - St VincentAmerica - Swift CurrentAmerica - TegucigalpaAmerica - Tell City, IndianaAmerica - ThuleAmerica - Thunder BayAmerica - TijuanaAmerica - TorontoAmerica - TortolaAmerica - Tucuman, ArgentinaAmerica - Ushuaia, ArgentinaAmerica - VancouverAmerica - Vevay, IndianaAmerica - Vincennes, IndianaAmerica - VirginAmerica - WhitehorseAmerica - Winamac, IndianaAmerica - WinnipegAmerica - YakutatAmerica - YellowknifeAntarctica - CaseyAntarctica - DavisAntarctica - Dumont D'UrvilleAntarctica - MacquarieAntarctica - MawsonAntarctica - McMurdoAntarctica - PalmerAntarctica - RotheraAntarctica - South PoleAntarctica - SyowaAntarctica - TrollAntarctica - VostokArctic - LongyearbyenAsia - AdenAsia - AlmatyAsia - AmmanAsia - AnadyrAsia - AqtauAsia - AqtobeAsia - AshgabatAsia - AshkhabadAsia - BaghdadAsia - BahrainAsia - BakuAsia - BangkokAsia - BeirutAsia - BishkekAsia - BruneiAsia - CalcuttaAsia - ChitaAsia - ChoibalsanAsia - ChongqingAsia - ChungkingAsia - ColomboAsia - DaccaAsia - DamascusAsia - DhakaAsia - DiliAsia - DubaiAsia - DushanbeAsia - GazaAsia - HarbinAsia - HebronAsia - Ho Chi MinhAsia - Hong KongAsia - HovdAsia - IrkutskAsia - IstanbulAsia - JakartaAsia - JayapuraAsia - JerusalemAsia - KabulAsia - KamchatkaAsia - KarachiAsia - KashgarAsia - KathmanduAsia - KatmanduAsia - KhandygaAsia - KolkataAsia - KrasnoyarskAsia - Kuala LumpurAsia - KuchingAsia - KuwaitAsia - MacaoAsia - MacauAsia - MagadanAsia - MakassarAsia - ManilaAsia - MuscatAsia - NicosiaAsia - NovokuznetskAsia - NovosibirskAsia - OmskAsia - OralAsia - Phnom PenhAsia - PontianakAsia - PyongyangAsia - QatarAsia - QyzylordaAsia - RangoonAsia - RiyadhAsia - SaigonAsia - SakhalinAsia - SamarkandAsia - SeoulAsia - ShanghaiAsia - SingaporeAsia - SrednekolymskAsia - TaipeiAsia - TashkentAsia - TbilisiAsia - TehranAsia - Tel AvivAsia - ThimbuAsia - ThimphuAsia - TokyoAsia - Ujung PandangAsia - UlaanbaatarAsia - Ulan BatorAsia - UrumqiAsia - Ust-NeraAsia - VientianeAsia - VladivostokAsia - YakutskAsia - YekaterinburgAsia - YerevanAtlantic - AzoresAtlantic - BermudaAtlantic - CanaryAtlantic - Cape VerdeAtlantic - FaeroeAtlantic - FaroeAtlantic - Jan MayenAtlantic - MadeiraAtlantic - ReykjavikAtlantic - South GeorgiaAtlantic - St HelenaAtlantic - StanleyAustralia - ACTAustralia - AdelaideAustralia - BrisbaneAustralia - Broken HillAustralia - CanberraAustralia - CurrieAustralia - DarwinAustralia - EuclaAustralia - HobartAustralia - LHIAustralia - LindemanAustralia - Lord HoweAustralia - MelbourneAustralia - NSWAustralia - NorthAustralia - PerthAustralia - QueenslandAustralia - SouthAustralia - SydneyAustralia - TasmaniaAustralia - VictoriaAustralia - WestAustralia - YancowinnaBrazil - AcreBrazil - De NoronhaBrazil - EastBrazil - WestCETCST6CDTCanada - AtlanticCanada - CentralCanada - East-SaskatchewanCanada - EasternCanada - MountainCanada - NewfoundlandCanada - PacificCanada - SaskatchewanCanada - YukonChile - ContinentalChile - Easter IslandCubaEETESTEST5EDTEgyptEireEtc - GMTEtc - GMT+0Etc - GMT+1Etc - GMT+10Etc - GMT+11Etc - GMT+12Etc - GMT+2Etc - GMT+3Etc - GMT+4Etc - GMT+5Etc - GMT+6Etc - GMT+7Etc - GMT+8Etc - GMT+9Etc - GMT-0Etc - GMT-1Etc - GMT-10Etc - GMT-11Etc - GMT-12Etc - GMT-13Etc - GMT-14Etc - GMT-2Etc - GMT-3Etc - GMT-4Etc - GMT-5Etc - GMT-6Etc - GMT-7Etc - GMT-8Etc - GMT-9Etc - GMT0Etc - GreenwichEtc - UCTEtc - UTCEtc - UniversalEtc - ZuluEurope - AmsterdamEurope - AndorraEurope - AthensEurope - BelfastEurope - BelgradeEurope - BerlinEurope - BratislavaEurope - BrusselsEurope - BucharestEurope - BudapestEurope - BusingenEurope - ChisinauEurope - CopenhagenEurope - DublinEurope - GibraltarEurope - GuernseyEurope - HelsinkiEurope - Isle of ManEurope - IstanbulEurope - JerseyEurope - KaliningradEurope - KievEurope - LisbonEurope - LjubljanaEurope - LondonEurope - LuxembourgEurope - MadridEurope - MaltaEurope - MariehamnEurope - MinskEurope - MonacoEurope - MoscowEurope - NicosiaEurope - OsloEurope - ParisEurope - PodgoricaEurope - PragueEurope - RigaEurope - RomeEurope - SamaraEurope - San MarinoEurope - SarajevoEurope - SimferopolEurope - SkopjeEurope - SofiaEurope - StockholmEurope - TallinnEurope - TiraneEurope - TiraspolEurope - UzhgorodEurope - VaduzEurope - VaticanEurope - ViennaEurope - VilniusEurope - VolgogradEurope - WarsawEurope - ZagrebEurope - ZaporozhyeEurope - ZurichGBGB-EireGMTGMT+0GMT-0GMT0GreenwichHSTHongkongIcelandIndian - AntananarivoIndian - ChagosIndian - ChristmasIndian - CocosIndian - ComoroIndian - KerguelenIndian - MaheIndian - MaldivesIndian - MauritiusIndian - MayotteIndian - ReunionIranIsraelJamaicaJapanKwajaleinLibyaMETMSTMST7MDTMexico - Baja NorteMexico - Baja SurMexico - GeneralNZNZ-CHATNavajoPRCPST8PDTPacific - ApiaPacific - AucklandPacific - BougainvillePacific - ChathamPacific - ChuukPacific - EasterPacific - EfatePacific - EnderburyPacific - FakaofoPacific - FijiPacific - FunafutiPacific - GalapagosPacific - GambierPacific - GuadalcanalPacific - GuamPacific - JohnstonPacific - KiritimatiPacific - KosraePacific - KwajaleinPacific - MajuroPacific - MarquesasPacific - MidwayPacific - NauruPacific - NiuePacific - NorfolkPacific - NoumeaPacific - Pago PagoPacific - PalauPacific - PitcairnPacific - PohnpeiPacific - PonapePacific - Port MoresbyPacific - RarotongaPacific - SaipanPacific - SamoaPacific - TahitiPacific - TarawaPacific - TongatapuPacific - TrukPacific - WakePacific - WallisPacific - YapPolandPortugalROCROKSingaporeTurkeyUCTUS - AlaskaUS - AleutianUS - ArizonaUS - CentralUS - East-IndianaUS - EasternUS - HawaiiUS - Indiana-StarkeUS - MichiganUS - MountainUS - PacificUS - Pacific-NewUS - SamoaUniversalW-SUWETZuluLoading... Each Tile's Time Zone  UTC  RunStopToggle DropdownLast run 7m ago⇧⌘↩Clear Cache &amp; Refresh⇧⌘DDownload as PDF...Download as CSVs⌥⇧SSend...⌥⌘S Schedule... Copy from LookML into a Space...  Go to Dashboard LookML </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>div#dashboard</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//div[@id='lk-title']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='lk-dashboard-stuck-header']/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SCCM'])[1]/following::div[9]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Video on Demand'])[2]/following::div[9]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div/div[2]/div/div</value>
   </webElementXpaths>
</WebElementEntity>
