<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_NetworkOverview</name>
   <tag></tag>
   <elementGuidId>864f6d80-96c5-4eec-b4f1-178e5a5a3673</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dashboard-text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>NetworkOverview</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/div[1]/div[@class=&quot;dashboard-elements&quot;]/div[@class=&quot;newspaper-layout dashboard-layout ng-scope&quot;]/div[@class=&quot;container-relative&quot;]/div[@class=&quot;jsnewspaper&quot;]/div[@class=&quot;grid&quot;]/div[@class=&quot;grid-element ng-scope&quot;]/div[@class=&quot;dashboard-element ng-isolate-scope&quot;]/lk-dashboard-text[@class=&quot;ng-scope&quot;]/div[@class=&quot;vis dashboard-text-wrapper&quot;]/div[@class=&quot;dashboard-text&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='dashboard']/div/div[2]/div/div/div/div[2]/div[19]/div/lk-dashboard-text/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go to VoD Summary'])[1]/following::div[9]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View your detailed Video on Demand metrics'])[1]/following::div[9]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[19]/div/lk-dashboard-text/div/div</value>
   </webElementXpaths>
</WebElementEntity>
