<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect_Start Month_plotrect</name>
   <tag></tag>
   <elementGuidId>06d17dab-3f74-438e-8171-5ab373a5449f</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>plotrect</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>396.25</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>157</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>-20</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>transparent</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dashboard&quot;)/div[1]/div[@class=&quot;dashboard-elements&quot;]/div[@class=&quot;newspaper-layout dashboard-layout ng-scope&quot;]/div[@class=&quot;container-relative&quot;]/div[@class=&quot;jsnewspaper&quot;]/div[@class=&quot;grid&quot;]/div[@class=&quot;grid-element ng-scope&quot;]/div[@class=&quot;dashboard-element ng-isolate-scope&quot;]/lk-vis-element[@class=&quot;ng-scope&quot;]/div[@class=&quot;vis&quot;]/div[@class=&quot;vis-header-note-and-wrapper&quot;]/div[@class=&quot;vis-wrapper-container&quot;]/div[@class=&quot;vis-wrapper-inner-container&quot;]/div[@class=&quot;vis-wrapper&quot;]/div[1]/lk-visualization-container[@class=&quot;vis-element ng-scope ng-isolate-scope&quot;]/div[1]/div[@class=&quot;vis-container&quot;]/div[@class=&quot;looker-chart looker-column looker-cartesian-chart&quot;]/svg[1]/g[@class=&quot;container&quot;]/g[@class=&quot;geoms&quot;]/rect[@class=&quot;plotrect&quot;]</value>
   </webElementProperties>
</WebElementEntity>
